lorawan-radio: Add the low power feature
lora-rs/lora-rs pull request #259
Opened 2024-05-28 16:27 UTC by pcurt

This feature allows to set the radio in low power mode when we are using a lorawan device.

The `low_power` is automatically called after a lorawan transmission,
this function is now calling the lora chip sleep function.

Consumption has been measured in sleep mode after a lorawan communication with a SX1262 module and is in the expected range (1µA), the others 6µA comes from others components.

![327426836-2c795886-8783-467a-9e88-cf8bc7916b95](https://github.com/lora-rs/lora-rs/assets/57074781/def5b78d-6409-475f-a5f4-d795414ee033)

2024-05-28 20:50 UTC, lucasgranberg commented on lorawan-device/src/async_device/radio.rs
No need to change the trait implementation. It only acts as a default so the impl is not required to do low_power.

2024-05-29 01:14 UTC, lthiery requested changes

2024-05-29 01:14 UTC, lthiery commented on lora-phy/src/lorawan_radio.rs
yea i think that'd be more idiomatic

2024-05-29 01:14 UTC, lthiery commented on lorawan-device/src/async_device/radio.rs
:100:

2024-05-29 05:46 UTC, pcurt commented on lora-phy/src/lorawan_radio.rs
Yes, I agree, thanks for the suggestion

2024-05-29 05:48 UTC, pcurt commented on lorawan-device/src/async_device/radio.rs
Yes, I have reverted the the modification

2024-05-29 06:55 UTC, lucasgranberg approved these changes
Looks good, thanks for the PR and for taking the time to measure this.

2024-05-29 07:35 UTC, plaes approved these changes

2024-05-29 14:05 UTC, lthiery approved these changes

2024-05-29 14:05 UTC, merged